### ISSUE TITLE
[FEATURE] - add support to use `editor.wordSeparators` for word boundaries

### ISSUE THREAD

**Issue by ctf0** [alefragnani/vscode-copy-word#21]
the reason behind this is atm when we try to copy/cut something like `"abc"`, the whole thing will be affected instead of what u would expect which is only `abc`.

**PS**
this doesnt happen with single quotes.

**Comment by alefragnani** [comment]
Hi @ctf0 ,

Right now, the extension uses the `document.getWordRangeAtPosition` VSCode API. I’m not sure it does respect this setting, but I guess it should, at least, based on its description. 

If that is the case, I’ll open an issue on VS Code repo, to fix/update the API.

Hope this helps

**Comment by ctf0** [comment]
i believe the api is faulty yes
