### ISSUE TITLE
[FEATURE] - Cut/Copy line if at left margin

### ISSUE THREAD

**Issue by dudeNumber4** [alefragnani/vscode-copy-word#46]
I want the word cut/copy/paste functionality, but I also want the existing VS Code functionality of cut/copy of the current line when the cursor is at the left margin.  I can't see how one would not want that.

[Here is my MR for this feature: ](https://github.com/alefragnani/vscode-copy-word/pull/45)

**Comment by alefragnani** [comment]
Just noticed this has already been requested in #20 

Closing it as duplicate. Let’s discuss on that one.
