### ISSUE TITLE
[BUG] - properties activationEvents and main must both be specified or must both be omitted

### ISSUE THREAD

**Issue by ctf0** [alefragnani/vscode-copy-word#62]
```
Version: 1.77.0-insider
Commit: 2a6bd78f745d3e6330c8ff7db5282dc582e117fd
Date: 2023-03-17T20:59:26.562Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes
```

`properties activationEvents and main must both be specified or must both be omitted`

no `activationEvents` in https://github.com/alefragnani/vscode-copy-word/blob/master/package.json

**Comment by alefragnani** [comment]
Hi @ctf0 ,

Yep, I noticed. It is a regression in VS Code https://github.com/microsoft/vscode/issues/176602.

Waiting for instructions...

**Comment by alefragnani** [comment]
In the meantime, you could reinstall the previous version using the Extension viewlet option.
