### ISSUE TITLE
[Pull Request] - overwrite word only when cursor is in middle of word

### ISSUE THREAD

**Issue by Krysl** [alefragnani/vscode-copy-word#63]
https://user-images.githubusercontent.com/5905801/235287283-e994b9bb-ee51-43cb-b0a2-a77c6852d5c3.mp4

commit: https://github.com/Krysl/vscode-copy-word/commit/1d7e61524e0921b8add6d1296e3c7a30b08beb89

- add a setting `copyWord.overwriteWordBehavior` (default false): 
    <img width="618" alt="Settings" src="https://user-images.githubusercontent.com/5905801/235287404-74e9767c-5547-48a7-bad4-2d1d1c5e8d3d.png">
    - add localization for chinese
- add tests for the feature

vsix package: https://github.com/Krysl/vscode-copy-word/releases/tag/v3.11.0

**Comment by alefragnani** [comment]
Hi @Krysl ,

Could you please provide more details about your request? 

Also, create a proper Pull Request, providing the source code of your changes, instead of a `.vsix` file.

Thank you.

**Comment by Krysl** [comment]
commit: https://github.com/Krysl/vscode-copy-word/commit/1d7e61524e0921b8add6d1296e3c7a30b08beb89

@alefragnani I have posted the commit link already. (Maybe it's too small so you missed it)

I created the true pull request just now: https://github.com/alefragnani/vscode-copy-word/pull/64

**Comment by Krysl** [comment]
@alefragnani 

this feature is pretty much what was mentioned in this comment： [20#issuecomment-1207359276](https://github.com/alefragnani/vscode-copy-word/issues/20#issuecomment-1207359276):

```
// original text
world

// put the cursor at the beginning of the word
// | is the cursor
|world

// paste something
// current behavior
hello

// expected behavior
helloworld
```
in https://github.com/alefragnani/vscode-copy-word/issues/20#issuecomment-1207411407 you say:
> the new Copy Word: Paste command, created in #40, reproduces the behavior you described. Which as I understand is the expected behavior of that issue. Pinging @dudeNumber4 to share its thoughts about the command created there.

my pull request gives the combine of  `original Paste command` and the `Copy Word: Paste command`

| original Word<br> (paste `bbb` as `\|`) | `original Paste command` | `Copy Word: Paste command`<br>by `#40` | my pull request |
| --------------------------------------- | :----------------------: | :------------------------------------: | :-------------: |
| `\|`aaaa                                |         bbbbaaaa         |                  bbbb                  |    bbbbaaaa     |
| aaaa`\|`                                |         aaaabbbb         |                  bbbb                  |    aaaabbbb     |
| aa`\|`aa                                |         aabbbbaa         |                  bbbb                  |      bbbb       |

**Comment by alefragnani** [comment]
Thanks for the details. 
If everything works fine, it should be available in the next release.

Thank you
